### ISSUE TITLE
User reviews for incident management tools

### ISSUE THREAD

**Issue by danielleitcs** [meirwah/awesome-incident-response#125]
This is a great list. Your readers might also find user reviews for all the major [incident management tools](https://www.itcentralstation.com/categories/it-alerting-and-incident-management/tzd/c802-sf-3) on IT Central Station to be helpful. 

For example, Everbridge IT Alerting is ranked as the top IT alerting and incident management tool according to our community. You can see what they have to say about this and other solutions [here](https://www.itcentralstation.com/products/everbridge-it-alerting-reviews/tzd/c802-sf-3). 

*Disclaimer: I work for IT Central Station.

**Comment by meirwah** [comment]
Thank @danielleitcs ,
But I see this less relevant  for current list, we are looking here for incident response tools for **Security** teams,  while the tools on the list you suggest are more relevant for IT teams.

Will close this, if you disagree , plz let me know you're thoughts ...
