### ISSUE TITLE
Why is MISP not included in the list? 

### ISSUE THREAD

**Issue by rezamalik** [meirwah/awesome-incident-response#152]
Why is MISP (https://github.com/MISP/MISP) the de facto standard security tool not included?

**Comment by PolarBearGod** [comment]
Because MISP is a threat intelligence platform and should be in the "Awesome Threat Intelligence" repo?

**Comment by meirwah** [comment]
@PolarBearGod is correct: https://github.com/hslatman/awesome-threat-intelligence

closing this one
