### ISSUE TITLE
Incident Response... or more?

### ISSUE THREAD

**Issue by hslatman** [meirwah/awesome-incident-response#21]
So, I saw some additions that lean towards forensic analysis, although they *can* be used in IR. Any guidelines regarding this 'boundary'? From practice I know the boundary is of course quite shallow.

**Comment by meirwah** [comment]
I think forensic analysis is important part of IR, so we need to cover both.. 
BUT still focus on IR...
don't you think?

**Comment by hslatman** [comment]
Certainly, there's a need for analysis during the IR process. A time period, e.g. 1 hour, but possibly different for others, would fit my mental model. All analysis taking place within that period could be considered IR, and thereafter forensic. What do you think about that? It would exclude software for performing advanced malware analysis, for example.

I think I will keep that as my soft boundary for including tools on this list. That said, that will actually loosen up a bit what I will include in this list ;-)

**Comment by meirwah** [comment]
I agree @hslatman with this apporach...  let's not drift to deep into malware analysis (there are other lists for that)...
