### ISSUE TITLE
Additional Tools

### ISSUE THREAD

**Issue by pidydx** [meirwah/awesome-incident-response#43]
It was suggested you might be interested in some of the tools mentioned here.  I am hoping to find more time to expand on them soon as some of them still need some work to be as useful as I would like.  
https://github.com/rshipp/awesome-malware-analysis/commit/f0266011bc2f556c288b4dc3c0796ccc9ca93abe

**Comment by meirwah** [comment]
Thanks @pidydx , I will take a look!

**Comment by meirwah** [comment]
@pidydx GRR is already on the list, the other two(Winjob , MetaFS) I think are not a good fit for this list (not focused at Incident Response)...

But feel free to catch me up in the DFIR slack channel (signup here : https://rishi28.typeform.com/to/sTbTI8)
To talk more on that...

**Comment by meirwah** [comment]
@pidydx can I close this?

**Comment by pidydx** [comment]
No problem!  Ideally I will eventually finish getting those two into GRR anyways for their core DFIR uses sooner rather than later.
