### ISSUE TITLE
VolDiff

### ISSUE THREAD

**Issue by aim4r** [meirwah/awesome-incident-response#89]
Suggestion to add VolDiff to the list of memory analysis tools.

VolDiff: Malware Memory Footprint Analysis based on Volatility 
https://github.com/aim4r/VolDiff

**Comment by meirwah** [comment]
looks like a good fit for list, can you open a Pull request for it?
according to the contrib guide:
https://github.com/meirwah/awesome-incident-response/blob/master/contributing.md

**Comment by meirwah** [comment]
added
